### NUMPY
- in the python have lists that are serve thr purpose of arrays but they are slow in process
- numpy aims to provide an array object that is up to 50  faster than traditional python lists.
- they array object in numpy is called ndarray
  

In [121]:
import numpy as np

In [122]:
#array creation
a = np.array(10) 
type(a)

numpy.ndarray

In [123]:
#zero dimensional
z=np.array(10)
z.ndim

0

In [124]:
#1- dimensional
o = np.array([10,20,30])
o.ndim

1

In [125]:
# 2- dimensional
t = np.array([[10,12,12,15]])
t.ndim

2

In [126]:
#3 -dimensional
th = np.array([[[10,2,3,5,6,7]]])
th.ndim

3

In [127]:
#change the data ofarray elements
a = np.array([10,20,30])

In [128]:
a.dtype

dtype('int32')

In [129]:
a = np.array([10,20,30], dtype = 'float')
a.dtype



dtype('float64')

In [130]:
a

array([10., 20., 30.])

In [131]:
a = np.array([10,20,30], dtype = 'float')
print(a.dtype)
print('hello')
a

float64
hello


array([10., 20., 30.])

# other ways of creating an array
1  arrange
2  linspace
3  zeros
4  ones
5 random

In [132]:
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [133]:
a = np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [134]:
b = np.linspace(1,2,5)
b

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [135]:
b = np.linspace(1,5,15)
b

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [136]:
b = np.linspace(1,5,15 , retstep=True)
b

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

In [137]:
z= np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [138]:
o =np.ones([3,3])
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [139]:
r = np.random.rand(5,5)
r

array([[0.75602566, 0.95209218, 0.77822383, 0.05271216, 0.3124015 ],
       [0.21242654, 0.312007  , 0.53246369, 0.86571363, 0.24382798],
       [0.87408827, 0.05729933, 0.87917657, 0.83093268, 0.15901517],
       [0.80708278, 0.65071371, 0.97586213, 0.15580848, 0.13358953],
       [0.74962764, 0.01265182, 0.35395464, 0.6398055 , 0.20547418]])

In [140]:
r = np.random.randint(5,size=10)
r

array([2, 4, 4, 4, 1, 1, 2, 1, 4, 4])

### Slicing and indexing  the array

In [141]:
a= np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [142]:
a[1,2]

4

In [143]:
a[0:,1:]

array([[2, 3],
       [3, 4]])

In [144]:
#1 and 4
a[[0,1],[0,2]]

array([1, 4])

In [145]:
#3 and 2
a[[0,1],[2,0]]

array([3, 2])

In [146]:
a[0,0]

1

In [147]:
a[1,1]

3

## Reshaping the arrays


In [148]:
a =np.random.rand(5,2)

In [149]:
a

array([[0.6560446 , 0.81324162],
       [0.94561706, 0.73574213],
       [0.97207423, 0.17705059],
       [0.7869384 , 0.28748255],
       [0.49168894, 0.81600771]])

In [150]:
a.reshape(2,5)


array([[0.6560446 , 0.81324162, 0.94561706, 0.73574213, 0.97207423],
       [0.17705059, 0.7869384 , 0.28748255, 0.49168894, 0.81600771]])

In [151]:
a.reshape(6,2)


ValueError: cannot reshape array of size 10 into shape (6,2)

In [152]:
a.reshape(10,1)

array([[0.6560446 ],
       [0.81324162],
       [0.94561706],
       [0.73574213],
       [0.97207423],
       [0.17705059],
       [0.7869384 ],
       [0.28748255],
       [0.49168894],
       [0.81600771]])

In [153]:
a.reshape(1,10)

array([[0.6560446 , 0.81324162, 0.94561706, 0.73574213, 0.97207423,
        0.17705059, 0.7869384 , 0.28748255, 0.49168894, 0.81600771]])

In [154]:
a.reshape(5,-1)

array([[0.6560446 , 0.81324162],
       [0.94561706, 0.73574213],
       [0.97207423, 0.17705059],
       [0.7869384 , 0.28748255],
       [0.49168894, 0.81600771]])

In [155]:
a.reshape(-1,5)

array([[0.6560446 , 0.81324162, 0.94561706, 0.73574213, 0.97207423],
       [0.17705059, 0.7869384 , 0.28748255, 0.49168894, 0.81600771]])

##### Aggregate functions
 - the python numpy aggregate functions are sum,min,max,mean,median,average,,product,std,variance,percentile and corrcoef

In [156]:
a.min()

0.17705059051421101

In [157]:
a.max()

0.9720742330855215

In [158]:
a.var()

0.06483221409947244

In [159]:
a.mean()

0.6681887838967114

In [160]:
a.std()

0.2546217078323693

#### Stacking 
 is used to join two different arrays
- vertical stacking
- horizotal stacking

In [161]:
a=np.array([1,2,3,4,5])
b=np.array([2,5,6,7,8])

In [162]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 2, 5, 6, 7, 8])

In [163]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [2, 5, 6, 7, 8]])